# Generated by Django 6.0.3 on 2026-03-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('place_id', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('category', models.CharField(choices=[('restaurant', 'Restaurant'), ('hotel', 'Hotel'), ('activity', 'Activity'), ('hangout', 'Hangout Spot'), ('leisure', 'Leisure')], default='restaurant', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('price_level', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
